modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "mossfix"
version = "${version}"
displayName = "Moss Fix"
authors = "Gamma_02"
description = '''
This mod patches moss to be better than the bare minimum required for a functional feature
'''
#logoFile = ""

[[dependencies.mossfix]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mossfix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mossfix]]
modId = "architectury"
mandatory = true
versionRange = "[10.0.9,)"
ordering = "AFTER"
side = "BOTH"